### ISSUE TITLE
Change Glowstone to a more up-to-date completed version of minecraft

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/minecraft-buildpack#2]
I recommend spigot.

**Comment by mhsjlw** [comment]
Updated to spigot 1.8.8

**Comment by TekkitCommando** [comment]
Smart choice :+1: xD G++ isn't ready to be used on production level servers

**Comment by mhsjlw** [comment]
@TekkitCommando Yes, unfortunately not yet.

**Comment by mhsjlw** [comment]
If you have any feature requests or ideas create an issue and I'd be happy to implement it as I have run out of ideas for this project. But at least it works and it is easy!

**Comment by TekkitCommando** [comment]
Ok!
